stages:
  - test

cache:
  paths:
    - node_modules/

test:
  stage: test
  image: beevelop/nodejs-python
  variables:
    DB_URL: "mongodb://mongo/food-api"
  services:
    - mongo
  script:
    - npm i
    - npm test